0 int _putchar(char c);
1 void print_alphabet(void);
2 void print_alphabet_x10(void);
3 int _islower(int c);
4 int _isalpha(int c);
5 int print_sign(int n);
6 int _abs(int);
7 int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
